import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import cliEnvelope from "../../api/fixtures/analyze/cli-parity.json";
import { decodeAnalyzeSnapshot } from "../../api/contract";
import { createAnalyzeIndex, selectDirectory, selectVisibleChildren } from "./selectors";

// Generated by reopen-generate-parity-fixture.ps1 and the real CLI. SHA-256 is
// over JSON.stringify(envelope.data), independent of checkout line endings.
const CLI_SNAPSHOT_SHA256 = "d14a6c33214dbb4a19527b6184411b68b02b90bec639fb9d8c94e08f7a3e1c36";

describe("Analyze identical-fixture parity", () => {
  it("keeps CLI totals, evidence, and warnings through the desktop decoder and selectors", () => {
    expect(createHash("sha256").update(JSON.stringify(cliEnvelope.data)).digest("hex"))
      .toBe(CLI_SNAPSHOT_SHA256);

    const snapshot = decodeAnalyzeSnapshot(cliEnvelope.data);
    const index = createAnalyzeIndex(snapshot);
    const root = selectDirectory(index, 0);
    const visible = selectVisibleChildren(root.children, "", "size_desc");
    const evidence = snapshot.nodes.reduce<Record<string, number>>((counts, node) => {
      counts[node.evidence] = (counts[node.evidence] ?? 0) + 1;
      return counts;
    }, {});
    const warnings = snapshot.warnings.reduce<Record<string, number>>((counts, warning) => {
      counts[warning.class] = (counts[warning.class] ?? 0) + 1;
      return counts;
    }, {});

    expect(snapshot.nodes).toHaveLength(7);
    expect(root.directory.bytes).toBe(8_388_616);
    expect(visible.reduce((bytes, node) => bytes + node.bytes, 0)).toBe(root.directory.bytes);
    expect(evidence).toEqual({ complete: 5, incomplete: 2 });
    expect(warnings).toEqual({ access_denied: 1 });
    expect(visible.find((node) => node.name === "sparse-logical.bin")).toMatchObject({
      bytes: 8_388_608,
      evidence: "complete",
    });
    expect(visible.find((node) => node.name === "denied")).toMatchObject({
      bytes: 0,
      evidence: "incomplete",
      warnings: ["access_denied"],
    });
  });
});
