// Generated by scripts/generate-types.mjs with quicktype-core from named JSON fixtures.
// Runtime validation remains in contract.ts; do not edit this file by hand.
export interface ActionFailure {
    message:   string;
    target_id: string;
}

export interface ActionKindCommand {
    irreversible: boolean;
    type:         "command";
}

export interface ActionKindInspectOnly {
    type: "inspect_only";
}

export interface ActionKindMoveToTrash {
    type: "move_to_trash";
}

export interface ActionKindPermanentDelete {
    type: "permanent_delete";
}

export interface CapacityEstimatePartial {
    lower_bound_bytes: number;
    type:              "partial";
}

export interface CapacityEstimateUnknown {
    type: "unknown";
}

export interface CapacityEstimateVerified {
    bytes: number;
    type:  "verified";
}

export interface CleanupIntentInspectOnly {
    rule_id: string;
    type:    "inspect_only";
}

export interface CleanupIntentRunBuiltInAction {
    action_id:   string;
    provider_id: string;
    type:        "run_built_in_action";
}

export interface CleanupIntentTrashProjectArtifact {
    rule_id: string;
    type:    "trash_project_artifact";
}

export interface CommandErrorInspectOnlyTarget {
    code:      "inspect_only_target";
    target_id: string;
}

export interface CommandErrorInvalidPlan {
    code:   "invalid_plan";
    issues: string[];
}

export interface CommandErrorIo {
    code:    "io";
    message: string;
}

export interface CommandErrorScanAlreadyRunning {
    code: "scan_already_running";
}

export interface CommandErrorScanFailed {
    code:    "scan_failed";
    message: string;
}

export interface CommandErrorStaleConfirmation {
    actual_digest:   string;
    code:            "stale_confirmation";
    expected_digest: string;
}

export interface CommandErrorUnknownTarget {
    code:      "unknown_target";
    target_id: string;
}

export interface DesktopScanProgress {
    message:  string;
    phase:    ScanPhase;
    preview:  ScanPreviewSnapshot | null;
    scan_id:  string;
    sequence: number;
}

export type ScanPhase = "global" | "projects";

export interface ScanPreviewSnapshot {
    targets: ScanPreviewTarget[];
    totals:  ScanPreviewTotals;
}

export interface ScanPreviewTarget {
    disposition:     ScanPreviewDisposition;
    ecosystem:       Ecosystem;
    estimated_bytes: number;
    evidence:        Evidence[];
    id:              string;
    kind:            TargetKind;
    last_modified:   SystemTime | null;
    path:            null | string;
    risk:            RiskLevel;
    scope:           Scope;
    size_complete:   boolean;
    sizing_warnings: SizingWarning[];
}

export type ScanPreviewDisposition = "candidate" | "inspect_only";

export type Ecosystem = "docker" | "generic" | "node" | "python" | "rust";

export type TargetKind = "build_artifacts" | "dependency_directory" | "package_cache" | "test_cache" | "tool_cache" | "virtual_env";

export interface SystemTime {
    nanos_since_epoch: number;
    secs_since_epoch:  number;
}

export type RiskLevel = "dangerous" | "high" | "low" | "medium";

export interface SizingWarning {
    detail: string;
    kind:   SizingWarningKind;
}

export type SizingWarningKind = "canceled" | "directory_entry_read_failed" | "directory_read_failed" | "entry_budget_exhausted" | "max_depth_reached" | "metadata_unavailable" | "path_unresolved" | "reparse_safety_unverified";

export interface ScanPreviewTotals {
    partial_lower_bound_bytes: number;
    target_count:              number;
    unknown_target_count:      number;
    verified_bytes:            number;
}

export interface ScanReport {
    health:  ScanHealth;
    plan:    UntrustedPlan;
    version: number;
}

export interface ScanHealth {
    completeness: ScanCompleteness;
    diagnostics:  ScanDiagnostic[];
    totals:       ScanTotals;
}

export type ScanCompleteness = "complete" | "partial";

export interface ScanDiagnostic {
    detail:   string;
    outcome:  ScanDiagnosticOutcome;
    path:     string;
    process?: ScanProcessProbe;
    stage:    ScanDiagnosticStage;
}

export type ScanDiagnosticOutcome = "canceled" | "failed" | "output_truncated" | "skipped";

export interface ScanProcessProbe {
    status: ScanProcessStatus;
    stderr: ScanProcessOutput;
    stdout: ScanProcessOutput;
}

export interface ScanProcessOutput {
    retained_bytes: number;
    total_bytes:    number;
    truncated:      boolean;
}

export type ScanDiagnosticStage = "cargo_metadata" | "discovery" | "provider" | "sizing";

export interface ScanTotals {
    partial_lower_bound_bytes: number;
    unknown_target_count:      number;
    verified_bytes:            number;
}

export interface UntrustedPlan {
    targets: UntrustedTarget[];
    version: number;
}

export interface UntrustedTarget {
    ecosystem:           Ecosystem;
    estimated_bytes:     number;
    evidence:            Evidence[];
    id:                  string;
    intent:              CleanupIntent;
    kind:                TargetKind;
    last_modified:       SystemTime | null;
    path:                null | string;
    reversible:          boolean;
    risk:                RiskLevel;
    rule_id:             string;
    scope:               Scope;
    selected_by_default: boolean;
    size_complete:       boolean;
    sizing_warnings?:    SizingWarning[];
}

export interface DesktopScanResultCanceled {
    scan_id: string;
    type:    "canceled";
}

export interface DesktopScanResultCompleted {
    report:  ScanReport;
    scan_id: string;
    type:    "completed";
}

export interface DryRunOutcome {
    digest: string;
    report: ExecutionReport;
}

export interface ExecutionReport {
    attempted:             number;
    audit_log:             null | string;
    confirmation_digest:   string;
    dry_run:               boolean;
    estimated_recoverable: ScanTotals;
    failed:                number;
    failures:              ActionFailure[];
    notes:                 ExecutionNote[];
    outcomes:              TargetOutcome[];
    selected:              number;
    skipped:               number;
    succeeded:             number;
}

export interface ExecutionNote {
    target_id: string;
    type:      "duplicate_selection_removed";
}

export interface TargetOutcome {
    action:                ActionKind;
    estimated_recoverable: CapacityEstimate;
    status:                OutcomeStatus;
    target_id:             string;
}

export interface EvidenceKnownCacheDir {
    path:   string;
    source: string;
    type:   "known_cache_dir";
}

export interface EvidenceMarkerFile {
    path: string;
    type: "marker_file";
}

export interface EvidenceOfficialCommand {
    command: string;
    type:    "official_command";
}

export interface EvidenceRuleMatched {
    rule_id: string;
    type:    "rule_matched";
}

export interface EvidenceUserConfigured {
    type: "user_configured";
}

export interface OutcomeStatusFailed {
    message: string;
    type:    "failed";
}

export interface OutcomeStatusSkipped {
    reason: string;
    type:   "skipped";
}

export interface OutcomeStatusSucceeded {
    type: "succeeded";
}

export interface ScanOptions {
    include_global:   boolean;
    include_projects: boolean;
    roots:            string[];
}

export interface ScanProcessStatusCanceled {
    type: "canceled";
}

export interface ScanProcessStatusExit {
    code: number | null;
    type: "exit";
}

export interface ScanProcessStatusInvalidOutput {
    type: "invalid_output";
}

export interface ScanProcessStatusNotFound {
    type: "not_found";
}

export interface ScanProcessStatusSuccess {
    type: "success";
}

export interface ScanProcessStatusTimeout {
    type: "timeout";
}

export interface ScopeGlobal {
    type: "global";
}

export interface ScopeProject {
    root: string;
    type: "project";
}

export type Scope = ScopeGlobal | ScopeProject;
export type Evidence = EvidenceKnownCacheDir | EvidenceMarkerFile | EvidenceOfficialCommand | EvidenceRuleMatched | EvidenceUserConfigured;
export type CleanupIntent = CleanupIntentInspectOnly | CleanupIntentRunBuiltInAction | CleanupIntentTrashProjectArtifact;
export type ScanProcessStatus = ScanProcessStatusCanceled | ScanProcessStatusExit | ScanProcessStatusInvalidOutput | ScanProcessStatusNotFound | ScanProcessStatusSuccess | ScanProcessStatusTimeout;
export type ActionKind = ActionKindCommand | ActionKindInspectOnly | ActionKindMoveToTrash | ActionKindPermanentDelete;
export type CapacityEstimate = CapacityEstimatePartial | CapacityEstimateUnknown | CapacityEstimateVerified;
export type OutcomeStatus = OutcomeStatusFailed | OutcomeStatusSkipped | OutcomeStatusSucceeded;
export type CommandError = CommandErrorInspectOnlyTarget | CommandErrorInvalidPlan | CommandErrorIo | CommandErrorScanAlreadyRunning | CommandErrorScanFailed | CommandErrorStaleConfirmation | CommandErrorUnknownTarget;
export type DesktopScanResult = DesktopScanResultCanceled | DesktopScanResultCompleted;
