// Generated by scripts/generate-types.mjs with quicktype-core from named JSON fixtures.
// Runtime validation remains in contract.ts; do not edit this file by hand.
export type AcState = "offline" | "online" | "unknown";

export interface ActionFailure {
    message:   string;
    target_id: string;
}

export interface ActionKindCommand {
    irreversible: boolean;
    type:         "command";
}

export interface ActionKindInspectOnly {
    type: "inspect_only";
}

export interface ActionKindMoveToTrash {
    type: "move_to_trash";
}

export interface ActionKindPermanentDelete {
    type: "permanent_delete";
}

export type AnalyzeCompleteness = "canceled" | "complete" | "partial_budget";

export type AnalyzeEvidence = "complete" | "incomplete" | "unknown";

export type AnalyzeNodeKind = "directory" | "file" | "reparse";

export interface AnalyzeNodeV1 {
    bytes:           number;
    evidence:        AnalyzeEvidence;
    id:              number;
    immediate_count: number;
    kind:            AnalyzeNodeKind;
    mtime_ms:        number | null;
    name:            string;
    parent_id:       number | null;
    recursive_count: number;
    warnings:        AnalyzeWarningClass[];
}

export type AnalyzeWarningClass = "access_denied" | "churn" | "cycle" | "duplicate_link" | "io_error" | "partial_budget" | "reparse";

export interface AnalyzeRootIdentity {
    input:      string;
    normalized: string;
    volume:     string;
}

export interface AnalyzeSnapshotV1 {
    accounted_owned_bytes: number;
    completeness:          AnalyzeCompleteness;
    nodes:                 AnalyzeNodeV1[];
    root:                  AnalyzeRootIdentity;
    version:               number;
    warnings:              AnalyzeWarningV1[];
}

export interface AnalyzeWarningV1 {
    class:   AnalyzeWarningClass;
    node_id: number | null;
}

export interface CapacityEstimatePartial {
    lower_bound_bytes: number;
    type:              "partial";
}

export interface CapacityEstimateUnknown {
    type: "unknown";
}

export interface CapacityEstimateVerified {
    bytes: number;
    type:  "verified";
}

export interface CleanMovedTotalsV1 {
    known_bytes:     number;
    lower_bound:     boolean;
    unknown_records: number;
}

export interface CleanupIntentInspectOnly {
    rule_id: string;
    type:    "inspect_only";
}

export interface CleanupIntentRunBuiltInAction {
    action_id:   string;
    provider_id: string;
    type:        "run_built_in_action";
}

export interface CleanupIntentTrashProjectArtifact {
    rule_id: string;
    type:    "trash_project_artifact";
}

export interface CommandErrorAnalyzeAlreadyRunning {
    code: "analyze_already_running";
}

export interface CommandErrorAnalyzeFailed {
    code:    "analyze_failed";
    message: string;
}

export interface CommandErrorHistoryNotFound {
    code:    "history_not_found";
    message: string;
}

export interface CommandErrorHistoryStoreUnavailable {
    code:    "history_store_unavailable";
    message: string;
}

export interface CommandErrorInspectOnlyTarget {
    code:      "inspect_only_target";
    target_id: string;
}

export interface CommandErrorInvalidPlan {
    code:   "invalid_plan";
    issues: string[];
}

export interface CommandErrorIo {
    code:    "io";
    message: string;
}

export interface CommandErrorOptimizeAlreadyRunning {
    code: "optimize_already_running";
}

export interface CommandErrorOptimizeAuditUnavailable {
    code:    "optimize_audit_unavailable";
    message: string;
}

export interface CommandErrorOptimizeFailed {
    code:    "optimize_failed";
    message: string;
}

export interface CommandErrorOptimizeStaleAuthority {
    code:    "optimize_stale_authority";
    message: string;
}

export interface CommandErrorOptimizeUnavailable {
    code:    "optimize_unavailable";
    message: string;
}

export interface CommandErrorProtectionAuditUnknown {
    code:    "protection_audit_unknown";
    message: string;
}

export interface CommandErrorProtectionConfirmationRequired {
    code:    "protection_confirmation_required";
    message: string;
}

export interface CommandErrorProtectionPathMissing {
    code:    "protection_path_missing";
    message: string;
}

export interface CommandErrorProtectionStoreUnavailable {
    code:    "protection_store_unavailable";
    message: string;
}

export interface CommandErrorRuleNotFound {
    code:    "rule_not_found";
    message: string;
}

export interface CommandErrorScanAlreadyRunning {
    code: "scan_already_running";
}

export interface CommandErrorScanFailed {
    code:    "scan_failed";
    message: string;
}

export interface CommandErrorSoftwareAlreadyRunning {
    code: "software_already_running";
}

export interface CommandErrorSoftwareAuditUnavailable {
    code:    "software_audit_unavailable";
    message: string;
}

export interface CommandErrorSoftwareFailed {
    code:    "software_failed";
    message: string;
}

export interface CommandErrorSoftwareStaleAuthority {
    code:    "software_stale_authority";
    message: string;
}

export interface CommandErrorStaleConfirmation {
    actual_digest:   string;
    code:            "stale_confirmation";
    expected_digest: string;
}

export interface CommandErrorStatusAlreadyRunning {
    code: "status_already_running";
}

export interface CommandErrorStatusFailed {
    code:    "status_failed";
    message: string;
}

export interface CommandErrorUnknownTarget {
    code:      "unknown_target";
    target_id: string;
}

export interface CpuAvailabilityV1 {
    age_ms?:            number;
    reason_code?:       string;
    sampled_at_unix_ms: number | null;
    state:              string;
    value?:             CpuV1;
}

export interface CpuV1 {
    system_utilization_basis_points: number;
}

export interface DesktopAnalyzeProgress {
    accounted_owned_bytes: number;
    changed_nodes:         AnalyzeNodeV1[];
    operation_id:          string;
    queue_depth:           number;
    sequence:              number;
    stored_nodes:          number;
}

export interface DesktopAnalyzeResultCanceled {
    operation_id: string;
    snapshot:     AnalyzeSnapshotV1;
    type:         "canceled";
}

export interface DesktopAnalyzeResultCompleted {
    operation_id: string;
    snapshot:     AnalyzeSnapshotV1;
    type:         "completed";
}

export interface DesktopOptimizeAuditResult {
    operation_id: string;
    records:      OptimizeAuditRecordV1[];
    recovered:    MaintenanceActionOutcomeV1[];
}

export interface OptimizeAuditRecordV1 {
    action_class:      MaintenanceActionClass;
    adapter_outcome?:  OptimizeAdapterOutcome;
    catalogue_id:      string;
    catalogue_version: number;
    domain:            string;
    error_code?:       OptimizeAuditErrorCode;
    operation_id:      string;
    preview_digest:    string;
    schema_version:    number;
    status_code:       OptimizeAuditStatusCode;
    timestamp_unix_ms: number;
    transition:        OptimizeAuditTransition;
}

export type MaintenanceActionClass = "execute" | "guidance" | "settings_handoff";

export type OptimizeAdapterOutcome = "failure" | "success" | "unfinished";

export type OptimizeAuditErrorCode = "adapter_canceled_after_dispatch" | "adapter_dispatch_failed" | "adapter_operation_failed" | "adapter_timed_out" | "recovered_after_crash";

export type OptimizeAuditStatusCode = "adapter_failed" | "adapter_succeeded" | "adapter_unfinished" | "canceled_before_start" | "dispatch_started" | "failed" | "launched" | "recovered_before_dispatch" | "succeeded" | "unknown_after_dispatch" | "validated";

export type MaintenanceExecutionOutcome = "canceled_before_start" | "failed" | "launched" | "succeeded" | "unknown_after_dispatch";

export interface MaintenanceActionOutcomeV1 {
    action_class: MaintenanceActionClass;
    catalogue_id: string;
    error_code?:  OptimizeAuditErrorCode;
    operation_id: string;
    outcome:      MaintenanceExecutionOutcome;
}

export interface MaintenanceCatalogueEntryV1 {
    action_class: MaintenanceActionClass;
    build_floor:  number | null;
    id:           string;
}

export interface DesktopOptimizeListResultCanceled {
    operation_id: string;
    type:         "canceled";
}

export interface DesktopOptimizeListResultCompleted {
    catalogue_version: number;
    entries:           MaintenanceCatalogueEntryV1[];
    operation_id:      string;
    type:              "completed";
}

export interface DesktopOptimizePreviewResult {
    operation_id: string;
    plan:         MaintenancePlanV1;
    preview:      MaintenancePreviewV1;
}

export interface MaintenancePlanV1 {
    catalogue_version: number;
    operation_id:      string;
    version:           number;
}

export interface MaintenancePreviewV1 {
    action_class:      MaintenanceActionClass;
    catalogue_version: number;
    digest:            string;
    operation_id:      string;
    version:           number;
}

export interface DesktopOptimizeRunResult {
    operation_id: string;
    report:       MaintenanceExecutionReportV1;
}

export interface MaintenanceExecutionReportV1 {
    catalogue_version: number;
    outcomes:          MaintenanceActionOutcomeV1[];
    version:           number;
}

export interface DesktopScanProgress {
    message:  string;
    phase:    ScanPhase;
    preview:  ScanPreviewSnapshot | null;
    scan_id:  string;
    sequence: number;
}

export type ScanPhase = "global" | "projects";

export interface ScanPreviewSnapshot {
    targets: ScanPreviewTarget[];
    totals:  ScanPreviewTotals;
}

export interface ScanPreviewTarget {
    disposition:     ScanPreviewDisposition;
    ecosystem:       Ecosystem;
    estimated_bytes: number;
    evidence:        Evidence[];
    id:              string;
    kind:            TargetKind;
    last_modified:   SystemTime | null;
    path:            null | string;
    risk:            RiskLevel;
    scope:           Scope;
    size_complete:   boolean;
    sizing_warnings: SizingWarning[];
}

export type ScanPreviewDisposition = "candidate" | "inspect_only";

export type Ecosystem = "docker" | "generic" | "node" | "python" | "rust";

export type TargetKind = "build_artifacts" | "dependency_directory" | "package_cache" | "test_cache" | "tool_cache" | "virtual_env";

export interface SystemTime {
    nanos_since_epoch: number;
    secs_since_epoch:  number;
}

export type RiskLevel = "dangerous" | "high" | "low" | "medium";

export interface SizingWarning {
    detail: string;
    kind:   SizingWarningKind;
}

export type SizingWarningKind = "canceled" | "directory_entry_read_failed" | "directory_read_failed" | "entry_budget_exhausted" | "max_depth_reached" | "metadata_unavailable" | "path_unresolved" | "reparse_safety_unverified";

export interface ScanPreviewTotals {
    partial_lower_bound_bytes: number;
    target_count:              number;
    unknown_target_count:      number;
    verified_bytes:            number;
}

export interface ScanReport {
    health:  ScanHealth;
    plan:    UntrustedPlan;
    version: number;
}

export interface ScanHealth {
    completeness: ScanCompleteness;
    diagnostics:  ScanDiagnostic[];
    totals:       ScanTotals;
}

export type ScanCompleteness = "complete" | "partial";

export interface ScanDiagnostic {
    detail:   string;
    outcome:  ScanDiagnosticOutcome;
    path:     string;
    process?: ScanProcessProbe;
    stage:    ScanDiagnosticStage;
}

export type ScanDiagnosticOutcome = "canceled" | "failed" | "output_truncated" | "skipped";

export interface ScanProcessProbe {
    status: ScanProcessStatus;
    stderr: ScanProcessOutput;
    stdout: ScanProcessOutput;
}

export interface ScanProcessOutput {
    retained_bytes: number;
    total_bytes:    number;
    truncated:      boolean;
}

export type ScanDiagnosticStage = "cargo_metadata" | "discovery" | "provider" | "sizing";

export interface ScanTotals {
    partial_lower_bound_bytes: number;
    unknown_target_count:      number;
    verified_bytes:            number;
}

export interface UntrustedPlan {
    targets: UntrustedTarget[];
    version: number;
}

export interface UntrustedTarget {
    ecosystem:           Ecosystem;
    estimated_bytes:     number;
    evidence:            Evidence[];
    id:                  string;
    intent:              CleanupIntent;
    kind:                TargetKind;
    last_modified:       SystemTime | null;
    path:                null | string;
    reversible:          boolean;
    risk:                RiskLevel;
    rule_id:             string;
    scope:               Scope;
    selected_by_default: boolean;
    size_complete:       boolean;
    sizing_warnings?:    SizingWarning[];
}

export interface DesktopScanResultCanceled {
    scan_id: string;
    type:    "canceled";
}

export interface DesktopScanResultCompleted {
    report:  ScanReport;
    scan_id: string;
    type:    "completed";
}

export interface DesktopSoftwareAuditResult {
    operation_id: string;
    records:      SoftwareAuditRecordV1[];
    recovered:    SoftwareActionOutcomeV1[];
}

export interface SoftwareAuditRecordV1 {
    adapter_outcome?:      SoftwareAdapterOutcome;
    domain:                string;
    error_code?:           SoftwareAuditErrorCode;
    identity:              SoftwareIdentity;
    installed_state?:      Software;
    inventory_fingerprint: string;
    irreversible:          boolean;
    operation_id:          string;
    preview_digest:        string;
    reboot_evidence:       SoftwareRebootEvidence;
    requery_result?:       Software;
    schema_version:        number;
    status_code:           SoftwareAuditStatusCode;
    timestamp_unix_ms:     number;
    transition:            SoftwareAuditTransition;
}

export type SoftwareAdapterOutcome = "failure" | "reboot_required" | "success" | "unfinished";

export type SoftwareAuditErrorCode = "adapter_cancel_failed" | "adapter_canceled_after_dispatch" | "adapter_dispatch_failed" | "adapter_operation_failed" | "adapter_status_unavailable" | "adapter_timed_out" | "recovered_after_crash" | "requery_conflicting" | "requery_unavailable";

export type Software = "absent" | "conflicting" | "present" | "unavailable";

export type SoftwareRebootEvidence = "none" | "required";

export type SoftwareAuditStatusCode = "adapter_failed" | "adapter_reboot_required" | "adapter_succeeded" | "canceled_before_start" | "dispatch_started" | "failed" | "reboot_required" | "recovered_before_dispatch" | "removed" | "requery_absent" | "requery_conflicting" | "requery_present" | "requery_unavailable" | "still_present" | "unknown_after_dispatch" | "validated";

export interface SoftwareActionOutcomeV1 {
    error_code?:      SoftwareAuditErrorCode;
    installed_state?: Software;
    irreversible:     boolean;
    operation_id:     string;
    outcome:          SoftwareExecutionOutcome;
    reboot_evidence:  SoftwareRebootEvidence;
    software_id:      string;
}

export type SoftwareExecutionOutcome = "canceled_before_start" | "failed" | "reboot_required" | "removed" | "still_present" | "unknown_after_dispatch";

export interface SoftwareInventoryV1 {
    entries:             SoftwareEntryV1[];
    fingerprint:         string;
    observed_at_unix_ms: number;
    sources:             SoftwareSourceEvidence[];
    version:             number;
}

export interface SoftwareEntryV1 {
    display_name?: string;
    eligibility:   SoftwareEligibility;
    id:            string;
    identity:      SoftwareIdentity;
    last_used:     SoftwareLastUsedEvidence;
    provenance:    SoftwareSourceId[];
    publisher?:    string;
    scope:         SoftwareScope;
    size:          SoftwareSizeEvidence;
    version?:      string;
}

export interface SoftwareEligibility {
    reason: SoftwareEligibilityReason;
    state:  SoftwareEligibilityState;
}

export type SoftwareEligibilityReason = "conflicting_identity" | "dependency_package" | "eligible_current_user_msix" | "hidden_entry" | "msi_execution_not_supported_v1" | "no_remove" | "protected_product" | "registry_only_manual" | "source_incomplete" | "stub_package" | "system_or_update" | "unhealthy_package" | "unsupported_source";

export type SoftwareEligibilityState = "manual" | "selectable";

export interface SoftwareLastUsedEvidence {
    reason_code: string;
    state:       "unknown";
}

export type SoftwareScope = "current_user" | "machine";

export interface SoftwareSourceEvidence {
    reason_code?: string;
    source:       SoftwareSourceId;
    state:        SoftwareSourceState;
}

export type SoftwareSourceState = "available" | "partial" | "permission" | "unsupported";

export interface DesktopSoftwareInventoryResultCanceled {
    operation_id: string;
    type:         "canceled";
}

export interface DesktopSoftwareInventoryResultCompleted {
    inventory:    SoftwareInventoryV1;
    operation_id: string;
    type:         "completed";
}

export interface SoftwareLeftoverPlanV1 {
    display_name?:          string;
    identity:               SoftwareIdentity;
    publisher?:             string;
    selected_candidate_ids: string[];
    software_id:            string;
    uninstall_operation_id: string;
    version:                number;
}

export interface SoftwareLeftoverAppV1 {
    app_size:      SoftwareSizeEvidence;
    candidates:    SoftwareLeftoverCandidateV1[];
    display_name?: string;
    identity:      SoftwareIdentity;
    publisher?:    string;
    software_id:   string;
}

export interface SoftwareLeftoverCandidateV1 {
    certainty:           SoftwareLeftoverCertainty;
    id:                  string;
    origin:              SoftwareLeftoverOrigin;
    path:                string;
    selected_by_default: boolean;
    size:                SoftwareSizeEvidence;
}

export type SoftwareLeftoverCertainty = "certain" | "uncertain";

export type SoftwareLeftoverOrigin = "install_location" | "local_app_data" | "program_data" | "roaming_app_data";

export interface DesktopSoftwareLeftoversPreviewResultDiscovered {
    operation_id: string;
    preview:      SoftwareLeftoverPreviewV1;
    type:         "discovered";
}

export interface SoftwareLeftoverPreviewV1 {
    apps:    SoftwareLeftoverAppV1[];
    version: number;
}

export interface DesktopSoftwareLeftoversPreviewResultPlanned {
    operation_id: string;
    plan:         SoftwareLeftoverPlanV1;
    preview:      SoftwareLeftoverPlanPreviewV1;
    type:         "planned";
}

export interface SoftwareLeftoverPlanPreviewV1 {
    digest:  string;
    items:   SoftwareLeftoverCandidateV1[];
    version: number;
}

export interface DesktopSoftwareLeftoversResult {
    operation_id: string;
    report:       SoftwareLeftoverReportV1;
}

export interface SoftwareLeftoverReportV1 {
    lower_bound:            boolean;
    moved_known_bytes:      number;
    operation_id:           string;
    outcomes:               SoftwareLeftoverOutcomeV1[];
    software_id:            string;
    uninstall_operation_id: string;
    version:                number;
}

export interface SoftwareLeftoverOutcomeV1 {
    candidate_id:     string;
    certainty:        SoftwareLeftoverCertainty;
    error_code?:      SoftwareSupportErrorCode;
    estimated_bytes?: number;
    outcome:          SoftwareSupportOutcomeCode;
}

export type SoftwareSupportErrorCode = "canceled" | "not_present" | "protected" | "registry_write_failed" | "trash_failed" | "unsafe_path" | "verification_failed";

export type SoftwareSupportOutcomeCode = "failed" | "skipped" | "succeeded";

export interface DesktopSoftwarePreviewResult {
    operation_id: string;
    plan:         SoftwareSelectionPlanV1;
    preview:      SoftwarePreviewV1;
}

export interface SoftwareSelectionPlanV1 {
    expires_at_unix_ms:            number;
    inventory_fingerprint:         string;
    inventory_observed_at_unix_ms: number;
    selected_ids:                  string[];
    version:                       number;
}

export interface SoftwarePreviewV1 {
    digest:                string;
    inventory_fingerprint: string;
    irreversible:          boolean;
    selected:              SoftwarePreviewItemV1[];
    version:               number;
}

export interface SoftwarePreviewItemV1 {
    action_class:   SoftwareActionClass;
    eligibility:    SoftwareEligibilityReason;
    id:             string;
    identity:       SoftwareIdentity;
    scope:          SoftwareScope;
    strategy_token: string;
}

export type SoftwareActionClass = "remove_current_user_msix";

export interface DesktopSoftwareUninstallResult {
    operation_id: string;
    report:       SoftwareExecutionReportV1;
}

export interface SoftwareExecutionReportV1 {
    irreversible: boolean;
    outcomes:     SoftwareActionOutcomeV1[];
    version:      number;
}

export interface DesktopSoftwareUpdatesResult {
    operation_id: string;
    updates:      SoftwareUpdatesV1;
}

export type SoftwareUpdatesReason = "canceled" | "non_zero_exit" | "output_truncated" | "process_failed" | "source_agreement_pending" | "timed_out" | "unrecognized_output" | "winget_missing";

export interface SoftwareUpdateRowV1 {
    available_version:    string;
    id:                   string;
    installed_version:    string;
    matched_software_ids: string[];
    name:                 string;
    name_truncated:       boolean;
    source:               string;
}

export interface DesktopStatusLiveResultCanceled {
    operation_id: string;
    type:         "canceled";
}

export interface DesktopStatusLiveResultCompleted {
    operation_id: string;
    type:         "completed";
}

export interface StatusSnapshotV1 {
    cpu:                      CpuAvailabilityV1;
    logical_processor_count:  number;
    memory:                   MemoryAvailabilityV1;
    network:                  NetworkAvailabilityV1;
    power:                    PowerAvailabilityV1;
    processes:                ProcessesAvailabilityV1;
    sample_window_ms:         number;
    sampled_at_unix_ms:       number;
    snapshot_id:              string;
    unsupported_capabilities: UnsupportedCapabilityV1[];
    volumes:                  VolumesAvailabilityV1;
}

export interface MemoryAvailabilityV1 {
    age_ms?:            number;
    reason_code?:       string;
    reason_codes?:      string[];
    sampled_at_unix_ms: number | null;
    state:              string;
    value?:             MemoryV1;
}

export interface MemoryV1 {
    available_bytes: number;
    total_bytes:     number;
    used_bytes:      number;
}

export interface NetworkAvailabilityV1 {
    age_ms?:            number;
    reason_code?:       string;
    sampled_at_unix_ms: number | null;
    state:              string;
    value?:             NetworkV1;
}

export interface NetworkV1 {
    interfaces:  NetworkInterfaceV1[];
    interval_ms: number;
}

export interface NetworkInterfaceV1 {
    interface_luid:      string;
    name:                string;
    rx_bytes_per_second: number;
    tx_bytes_per_second: number;
}

export interface PowerAvailabilityV1 {
    age_ms?:            number;
    reason_code?:       string;
    sampled_at_unix_ms: number | null;
    state:              string;
    value?:             PowerV1;
}

export interface PowerV1 {
    ac_state:            string;
    battery_present:     boolean;
    charge_basis_points: number | null;
    remaining_seconds:   number | null;
}

export interface ProcessesAvailabilityV1 {
    age_ms?:            number;
    reason_code?:       string;
    reason_codes?:      string[];
    sampled_at_unix_ms: number | null;
    state:              string;
    value?:             ProcessesV1;
}

export interface ProcessesV1 {
    budget_exhausted:    boolean;
    detail_budget_ms:    number;
    enumerated_count:    number;
    enumeration_ceiling: number;
    items:               ProcessV1[];
    requested_limit:     number;
    returned_count:      number;
    truncated_by_limit:  boolean;
}

export interface ProcessV1 {
    cpu_basis_points_of_one_logical_core: number;
    name:                                 string;
    pid:                                  number;
    private_bytes:                        number;
    read_bytes_per_second:                number;
    write_bytes_per_second:               number;
}

export interface UnsupportedCapabilityV1 {
    code:        string;
    reason_code: string;
    state:       string;
}

export interface VolumesAvailabilityV1 {
    age_ms?:            number;
    reason_code?:       string;
    sampled_at_unix_ms: number | null;
    state:              string;
    value?:             VolumesV1;
}

export interface VolumesV1 {
    complete: boolean;
    items:    VolumeV1[];
}

export interface VolumeV1 {
    available_bytes: number;
    mount_points:    string[];
    total_bytes:     number;
    volume_id:       string;
}

export interface DesktopStatusSnapshotResultCanceled {
    operation_id: string;
    type:         "canceled";
}

export interface DesktopStatusSnapshotResultCompleted {
    operation_id: string;
    snapshot:     StatusSnapshotV1;
    type:         "completed";
}

export interface DryRunOutcome {
    digest: string;
    report: ExecutionReport;
}

export interface ExecutionReport {
    attempted:             number;
    audit_log:             null | string;
    confirmation_digest:   string;
    dry_run:               boolean;
    estimated_recoverable: ScanTotals;
    failed:                number;
    failures:              ActionFailure[];
    notes:                 ExecutionNote[];
    outcomes:              TargetOutcome[];
    selected:              number;
    skipped:               number;
    succeeded:             number;
}

export interface ExecutionNote {
    target_id: string;
    type:      "duplicate_selection_removed";
}

export interface TargetOutcome {
    action:                ActionKind;
    estimated_recoverable: CapacityEstimate;
    status:                OutcomeStatus;
    target_id:             string;
}

export interface EvidenceKnownCacheDir {
    path:   string;
    source: string;
    type:   "known_cache_dir";
}

export interface EvidenceMarkerFile {
    path: string;
    type: "marker_file";
}

export interface EvidenceOfficialCommand {
    command: string;
    type:    "official_command";
}

export interface EvidenceRuleMatched {
    rule_id: string;
    type:    "rule_matched";
}

export interface EvidenceUserConfigured {
    type: "user_configured";
}

export type MsiContext = "machine" | "user_managed" | "user_unmanaged";

export interface OptimizeAuditTransitionAdapterCompleted {
    kind: "adapter_completed";
}

export interface OptimizeAuditTransitionDispatchStarted {
    kind: "dispatch_started";
}

export interface OptimizeAuditTransitionTerminal {
    kind:    "terminal";
    outcome: MaintenanceExecutionOutcome;
}

export interface OptimizeAuditTransitionValidated {
    kind: "validated";
}

export interface OutcomeStatusFailed {
    message: string;
    type:    "failed";
}

export interface OutcomeStatusSkipped {
    reason: string;
    type:   "skipped";
}

export interface OutcomeStatusSucceeded {
    type: "succeeded";
}

export type RegistryHive = "current_user" | "local_machine";

export type RegistryView = "registry32" | "registry64";

export interface ScanOptions {
    include_global:   boolean;
    include_projects: boolean;
    roots:            string[];
}

export interface ScanProcessStatusCanceled {
    type: "canceled";
}

export interface ScanProcessStatusExit {
    code: number | null;
    type: "exit";
}

export interface ScanProcessStatusInvalidOutput {
    type: "invalid_output";
}

export interface ScanProcessStatusNotFound {
    type: "not_found";
}

export interface ScanProcessStatusSuccess {
    type: "success";
}

export interface ScanProcessStatusTimeout {
    type: "timeout";
}

export interface ScopeGlobal {
    type: "global";
}

export interface ScopeProject {
    root: string;
    type: "project";
}

export interface SoftwareAuditTransitionAdapterCompleted {
    kind: "adapter_completed";
}

export interface SoftwareAuditTransitionDispatchStarted {
    kind: "dispatch_started";
}

export interface SoftwareAuditTransitionRequeryObserved {
    kind: "requery_observed";
}

export interface SoftwareAuditTransitionTerminal {
    kind:    "terminal";
    outcome: string;
}

export interface SoftwareAuditTransitionValidated {
    kind: "validated";
}

export interface SoftwareIdentityArp {
    hive:   string;
    source: "arp";
    subkey: string;
    view:   string;
}

export interface SoftwareIdentityMsi {
    context:      string;
    product_code: string;
    source:       "msi";
}

export interface SoftwareIdentityMsix {
    package_full_name: string;
    source:            "msix";
}

export type SoftwareLastUsedReason = "no_supported_exact_source";

export interface SoftwareLeftoverSelectionV1 {
    selected_candidate_ids: string[];
    software_id:            string;
    uninstall_operation_id: string;
}

export type SoftwareSizeBasis = "measured_directory" | "measured_installed_location" | "reported_estimate";

export interface SoftwareSizeEvidenceAvailable {
    basis:               string;
    observed_at_unix_ms: number;
    source_code:         string;
    state:               "available";
    value_bytes:         number;
}

export interface SoftwareSizeEvidencePartial {
    basis:               string;
    lower_bound_bytes:   number;
    observed_at_unix_ms: number;
    reason_code:         string;
    source_code:         string;
    state:               "partial";
}

export interface SoftwareSizeEvidenceUnknown {
    reason_code: string;
    state:       "unknown";
}

export type SoftwareSizeSourceCode = "arp_estimated_size_kib" | "leftover_directory" | "msi_estimated_size_kib" | "msix_installed_path";

export interface SoftwareSourceIdArp {
    hive:   string;
    source: "arp";
    view:   string;
}

export interface SoftwareSourceIdMsi {
    context: string;
    source:  "msi";
}

export interface SoftwareSourceIdMsixCurrentUser {
    source: "msix_current_user";
}

export interface SoftwareStartupEntryV1 {
    id:       string;
    location: SoftwareStartupLocation;
    name:     string;
    scope:    SoftwareScope;
    state:    SoftwareStartupState;
    toggle:   SoftwareStartupToggle;
}

export type SoftwareStartupLocation = "current_user_run" | "current_user_startup_folder" | "machine_run" | "machine_run32";

export type SoftwareStartupState = "disabled" | "enabled" | "unknown";

export type SoftwareStartupToggle = "allowed" | "requires_administrator";

export interface SoftwareStartupListV1 {
    entries:             SoftwareStartupEntryV1[];
    observed_at_unix_ms: number;
    sources:             SoftwareStartupSourceV1[];
    version:             number;
}

export interface SoftwareStartupSourceV1 {
    location:     SoftwareStartupLocation;
    reason_code?: string;
    state:        SoftwareSourceState;
}

export interface SoftwareStartupToggleReportV1 {
    entry:             SoftwareStartupEntryV1;
    error_code?:       SoftwareSupportErrorCode;
    operation_id:      string;
    outcome:           SoftwareSupportOutcomeCode;
    requested_enabled: boolean;
    version:           number;
}

export interface SoftwareUpdatesV1Available {
    observed_at_unix_ms: number;
    rows:                SoftwareUpdateRowV1[];
    state:               "available";
    version:             number;
}

export interface SoftwareUpdatesV1Unavailable {
    observed_at_unix_ms: number;
    reason_code:         SoftwareUpdatesReason;
    state:               "unavailable";
    version:             number;
}

export interface StatusEventV1Snapshot {
    data:               StatusSnapshotV1;
    emitted_at_unix_ms: number;
    event:              "status_snapshot";
    operation_id:       string;
    schema_version:     number;
    sequence:           number;
}

export interface StatusEventV1Started {
    data:               StatusStartedV1;
    emitted_at_unix_ms: number;
    event:              "status_started";
    operation_id:       string;
    schema_version:     number;
    sequence:           number;
}

export interface StatusStartedV1 {
    interval_ms:   number;
    process_limit: number;
}

export interface StatusEventV1Terminal {
    data:               StatusTerminalV1;
    emitted_at_unix_ms: number;
    event:              "status_terminal";
    operation_id:       string;
    schema_version:     number;
    sequence:           number;
}

export interface StatusTerminalV1 {
    error_code: null | string;
    reason:     string;
}

export interface StatusEventV1TickSkipped {
    data:               TickSkippedV1;
    emitted_at_unix_ms: number;
    event:              "tick_skipped";
    operation_id:       string;
    schema_version:     number;
    sequence:           number;
}

export interface TickSkippedV1 {
    reason:        string;
    skipped_total: number;
}

export type TerminalReason = "broken_pipe" | "canceled" | "completed" | "producer_error";

export type TickSkipReason = "sample_in_flight";

export type UnsupportedCapabilityState = "unsupported";

export type UnsupportedCode = "fan" | "gpu_utilization" | "physical_disk_activity" | "smart" | "thermal" | "vram";

export type Scope = ScopeGlobal | ScopeProject;
export type Evidence = EvidenceKnownCacheDir | EvidenceMarkerFile | EvidenceOfficialCommand | EvidenceRuleMatched | EvidenceUserConfigured;
export type CleanupIntent = CleanupIntentInspectOnly | CleanupIntentRunBuiltInAction | CleanupIntentTrashProjectArtifact;
export type ScanProcessStatus = ScanProcessStatusCanceled | ScanProcessStatusExit | ScanProcessStatusInvalidOutput | ScanProcessStatusNotFound | ScanProcessStatusSuccess | ScanProcessStatusTimeout;
export type ActionKind = ActionKindCommand | ActionKindInspectOnly | ActionKindMoveToTrash | ActionKindPermanentDelete;
export type CapacityEstimate = CapacityEstimatePartial | CapacityEstimateUnknown | CapacityEstimateVerified;
export type OutcomeStatus = OutcomeStatusFailed | OutcomeStatusSkipped | OutcomeStatusSucceeded;
export type CommandError = CommandErrorAnalyzeAlreadyRunning | CommandErrorAnalyzeFailed | CommandErrorHistoryNotFound | CommandErrorHistoryStoreUnavailable | CommandErrorInspectOnlyTarget | CommandErrorInvalidPlan | CommandErrorIo | CommandErrorOptimizeAlreadyRunning | CommandErrorOptimizeAuditUnavailable | CommandErrorOptimizeFailed | CommandErrorOptimizeStaleAuthority | CommandErrorOptimizeUnavailable | CommandErrorProtectionAuditUnknown | CommandErrorProtectionConfirmationRequired | CommandErrorProtectionPathMissing | CommandErrorProtectionStoreUnavailable | CommandErrorRuleNotFound | CommandErrorScanAlreadyRunning | CommandErrorScanFailed | CommandErrorSoftwareAlreadyRunning | CommandErrorSoftwareAuditUnavailable | CommandErrorSoftwareFailed | CommandErrorSoftwareStaleAuthority | CommandErrorStaleConfirmation | CommandErrorStatusAlreadyRunning | CommandErrorStatusFailed | CommandErrorUnknownTarget;
export type DesktopScanResult = DesktopScanResultCanceled | DesktopScanResultCompleted;
export type DesktopAnalyzeResult = DesktopAnalyzeResultCanceled | DesktopAnalyzeResultCompleted;
export type SoftwareSourceId = SoftwareSourceIdArp | SoftwareSourceIdMsi | SoftwareSourceIdMsixCurrentUser;
export type SoftwareIdentity = SoftwareIdentityArp | SoftwareIdentityMsi | SoftwareIdentityMsix;
export type SoftwareSizeEvidence = SoftwareSizeEvidenceAvailable | SoftwareSizeEvidencePartial | SoftwareSizeEvidenceUnknown;
export type SoftwareAuditTransition = SoftwareAuditTransitionAdapterCompleted | SoftwareAuditTransitionDispatchStarted | SoftwareAuditTransitionRequeryObserved | SoftwareAuditTransitionTerminal | SoftwareAuditTransitionValidated;
export type DesktopSoftwareInventoryResult = DesktopSoftwareInventoryResultCanceled | DesktopSoftwareInventoryResultCompleted;
export type DesktopOptimizeListResult = DesktopOptimizeListResultCanceled | DesktopOptimizeListResultCompleted;
export type DesktopStatusSnapshotResult = DesktopStatusSnapshotResultCanceled | DesktopStatusSnapshotResultCompleted;
export type DesktopStatusLiveResult = DesktopStatusLiveResultCanceled | DesktopStatusLiveResultCompleted;
export type StatusEventV1 = StatusEventV1Snapshot | StatusEventV1Started | StatusEventV1Terminal | StatusEventV1TickSkipped;
export type SoftwareUpdatesV1 = SoftwareUpdatesV1Available | SoftwareUpdatesV1Unavailable;
export type DesktopSoftwareLeftoversPreviewResult = DesktopSoftwareLeftoversPreviewResultDiscovered | DesktopSoftwareLeftoversPreviewResultPlanned;
export type OptimizeAuditTransition = OptimizeAuditTransitionAdapterCompleted | OptimizeAuditTransitionDispatchStarted | OptimizeAuditTransitionTerminal | OptimizeAuditTransitionValidated;
